### PR TITLE
Mag p

### PR DESCRIPTION
**Pull request by SWeinmueller**
Return the correct mag _P

### CODE REVIEW

**Comment by J-Endres** [comment]
Do we have consensus that we rather want the magnetization including encoding etc. than without? Or should we provide an additional flag to select this?

**Comment by SWeinmueller** [comment]
I see no application where we need the signal without relaxation, but we could use another flag to be more general and we don't have to decide now.

**Comment by mzaiss** [comment]
sounds interesting to have both options...

so you could get mri signals and the mag at the same time, still i wonder
how spoiling affects this...

is running an unencoded experiment then the same?
probably not as spoiling is missing in unencoded.

do you get mag at any timepoint or only at adc?

SWeinmueller ***@***.***> schrieb am Di., 10. Dez. 2024,
09:40:

**Comment by J-Endres** [comment]
We could have the option to return either + states or ADC mag, as made here: #101 

If that's okay, merge into mag_p before merging mag_p into main

**Comment by J-Endres** [comment]
Suggested change: remove `return_mag_z` and `return_mag_p` in favor of a `clear_mag_state` flag that defaults to false - this allows to extract all the data from the graph object, including magnetization.
`return_mag_adc` stays.

Example usage:
```python
graph = mr0.compute_graph(seq, data)
signal, mag_adc = mr0.execute_graph(graph, seq, data, return_mag_adc=True, clear_state_mag=False)

# Extract all states of the desired type and if it was simulated (mag is not None)
mag_p = [[state.mag for state in rep if state.dist_type == "+" and state.mag is not None] for rep in graph]
mag_z = [[state.mag for state in rep if state.dist_type in ["z", "z0"] and state.mag is not None] for rep in graph]
```

**Comment by SWeinmueller** [comment]
It works as desired. Nevertheless, you have to think carefully about which states you take into account, as some of these are also dephased.

**Comment by SWeinmueller** [comment]
mag_adc:

```
img = torch.zeros([*sz], dtype=torch.complex64)
mag = torch.stack([m[0] for m in mag_adc])
rows = 8
cols = 8
factor = int(sz[0] / rows)

# Generate plots for each subplot
plt.figure(dpi=300)
plt.suptitle("Transversal adc Mag", fontsize=16)
for i in range(rows):
    for j in range(cols):
        plt.subplot(rows, cols, i * cols + j + 1)
        img[obj_p.recover().PD>0] = mag[i*factor,j*factor,:]
        util.plot3D(img.abs())
        plt.clim(0,0.15)
        plt.axis('off')
# Show the plot
plt.show()

# Generate plots for each subplot
plt.figure(dpi=300)
plt.suptitle("Transversal adc Mag", fontsize=16)
for i in range(rows):
    for j in range(cols):
        plt.subplot(rows, cols, i * cols + j + 1)
        img[obj_p.recover().PD>0] = mag[i*factor,j*factor,:]
        util.plot3D(img.angle())
        plt.clim(0,0.15)
        plt.axis('off')
# Show the plot
plt.show()
```

grafik
grafik

**Pull request merged**
